### ISSUE TITLE
User adding/removing players from his team

### ISSUE THREAD

**Issue by emmanuelobo** [EmmanuelObo/stat-watch#2]
User will be able to add and remove players from his team.

#### Tasks:
- [x] Create/design 'team' page
- [x] Create 'add' function
- [x] Create 'remove' function
- [x] Build proper db object mappings
